export const CRIME_OPTIONS = [
  "Abduction",
  "Abscond Bail",
  "Aggravated Assault",
  "Aiding and Abetting",
  "Arson",
  "Bank Fraud",
  "Breach of Condition of Bail",
  "Breach of Excise Duty Act",
  "Breach of the Disaster Risk Management Act",
  "Burglary",
  "Burglary Habitation",
  "Carnal Abuse",
  "Child Abuse",
  "Child in Need of Care & Protection",
  "Child Pornography",
  "Contraband",
  "Corruption",
  "Crime of the Month",
  "Dead Body",
  "Drugs - Cocaine",
  "Drugs - Marijuana",
  "Escapee",
  "Forgery",
  "Fraud",
  "Fraudulent Use of License Plate",
  "Fugitive",
  "Gunmen",
  "Harboring Fugitive",
  "Homicide",
  "House Breaking",
  "Human Trafficking",
  "Illegal Activities",
  "Illegal Firearm/Ammo",
  "Illegal Gambling",
  "Illegal Immigrant",
  "Illegal Sale of Petrol",
  "Illicit Goods",
  "Incest",
  "Kidnapping",
  "Larceny",
  "Lottery Scamming",
  "Missing Person",
  "MOCA Tip Line",
  "Murder",
  "Person of Interest",
  "Planned Murder",
  "Praedial Larceny",
  "Query",
  "Rape",
  "Robbery",
  "Robbery with Aggravation",
  "Sacrilege",
  "Sexual Assault",
  "Shooting with Intent",
  "Stolen Motor Vehicle",
  "Stolen Property",
  "Suspicious Activities",
  "Suspicious Person",
  "Terrorism",
  "Theft",
  "Threat",
  "Uncustomed Goods",
  "Unlawful Discharge of Firearm",
  "Wanted Person",
  "Warrant",
  "Other",
]



